apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadhqhh7715-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadhqhh7715-tenant-component
    app.kubernetes.io/part-of: loadhqhh7715-tenant-app
  name: loadhqhh7715-tenant-component
  namespace: loadhqhh7715-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadhqhh7715-tenant-component
status:
  loadBalancer: {}
